"""
MongoDB Document Schema: ChatHistory

Collection: chat_history

Document structure:
{
    "_id": ObjectId,               # Auto-generated by MongoDB
    "user_id": "user123",
    "persona": "friend",
    "message": "Hello!",           # User's message
    "response": "Hey there! 😊",  # AI response
    "timestamp": datetime          # UTC timestamp
}

Indexes:
- (user_id, persona): compound index
- timestamp: single index
"""
